---
- taxonomy: 常用推荐
  icon: far fa-star
  links:
    - title: 频道页面
      logo: https://jsd.cdn.noisework.cn/gh/rcy1314/tuchuang@main/uPic/7877y.jpeg
      url: https://tg.noisework.cn
      description: 我的TG频道页面
    - title: 说说笔记
      logo: https://s2.loli.net/2025/04/07/fgn9WUwZbcGXpDk.png
      url: https://note.noisework.cn
      description: 个人朋友圈说说
- taxonomy: 媒体创作
  icon: fas fa-folder-open fa-lg
  list:
    - term: CG三维
      links:
        - title: CG爱好者
          logo: www.cgahz.com.ico
          url: http://www.cgahz.com
          description: 影视后期相关资源
        - title: CG99-CG设计网
          logo: cg99.ico
          url: https://www.cg99.com
          description: 专注全球CG设计行业，以CG模型为主的资源下载和分享平台
    - term: 模版插件
      links:
        - title: LOOKAE大众脸
          logo: www.lookae.com.ico
          url: https://www.lookae.com
          description: 最好的后期资源站
        - title: V后期资源吧
          logo: www.vfx123.com.ico
          url: https://www.vfx123.com
          description: 以FCPX资源为主